config:
  target: 'http://localhost:3000'
  phases:
    - duration: 60
      arrivalRate: 10
      name: 'Teste leve de carga no endpoint /v1/products'
  defaults:
    headers:
      Content-Type: 'application/json'

scenarios:
  - name: 'GET /v1/products'
    flow:
      - get:
          url: '/v1/products'
