services:
  postgres:
    image: postgres:15
    container_name: ecommerce-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dev/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce_network
    ports:
      - "5432:5432"

  ecommerce-api-1:
    image: ecommerce-api
    container_name: ecommerce-api-1
    env_file: .docker.env
    depends_on:
      - postgres
    networks:
      - ecommerce_network

  ecommerce-api-2:
    image: ecommerce-api
    container_name: ecommerce-api-2
    env_file: .docker.env
    depends_on:
      - postgres
    networks:
      - ecommerce_network

  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    depends_on:
      - ecommerce-api-1
      - ecommerce-api-2
    networks:
      - ecommerce_network

networks:
    ecommerce_network:
      name: ecommerce_network
      driver: bridge
